CarTireRepairService/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CarTireRepairService.Models;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Persistence.Models;
using Persistence.Services;

namespace CarTireRepairService.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly CTRService _service;
        private readonly UserManager<Client> _userManager;
        private IPagedList<DateTime> _dateTimes;

        private Reservation _inProgressReservation;


        public ReservationsController(CTRService service, UserManager<Client> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        // GET: Reservations
        public ViewResult Index(Int32? ID, ServiceTypes serviceType, Int32? page)
        {
            if (ID == null)
            {
                return View();
            }
            var temp = Enumerable.Range(00, 08).Select(i => Enumerable.Range(0, 2).Select(j => new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, i + 8, j * 30, 0)).ToList()).ToList();
            var reservations = _service.GetReservationsByWorkshopID((int)ID);
            List<DateTime> dateTimes = new List<DateTime>();
            for (int i = 0; i < 7; i++)
            {
                foreach (var elem in temp)
                {
                    foreach (var twoelem in elem)
                    {
                        var withAddedDay = twoelem.AddDays(i);
                        dateTimes = dateTimes.Append(withAddedDay).ToList();
                    }
                }
            }

            foreach (var reservation in reservations)
            {
                dateTimes = dateTimes.Where(d => d != reservation.ReservationTime).ToList();
            }
            ViewBag.ReservationTimes = dateTimes;

            var pageNumber = page ?? 1;
            _dateTimes = dateTimes.ToPagedList(pageNumber, 10);

            //ViewBag.OnePageAvailableReservations = onePageAvailableReservations;
            ViewBag.ID = ID;
            ViewBag.ServiceType = serviceType;

            return View(_dateTimes);
        }

        public IActionResult Create(Int32? ID, ServiceTypes serviceType, string chosenDateTime)
        {
            if (ID == null)
            {
                return NotFound();
            }

            try
            {
                CultureInfo provider = CultureInfo.InvariantCulture;
                var chosenDate = DateTime.ParseExact(chosenDateTime, "yyyyMMddHHmmss", provider);

                _inProgressReservation = new Reservation();
                _inProgressReservation.ProvidedService = new CarServices();
                _inProgressReservation.UserID = Int32.Parse(_userManager.GetUserId(User));
                _inProgressReservation.ReservationTime = chosenDate;
                _inProgressReservation.Workshop = _service.GetWorkShopByID((int)ID);
                switch (serviceType)
                {
                    case ServiceTypes.TireReplacement:
                        _inProgressReservation.ProvidedService.TireReplacement = true;
                        break;
                    case ServiceTypes.AirConCharging:
                        _inProgressReservation.ProvidedService.AirConCharging = true;
                        break;
                    case ServiceTypes.PunctureRepair:
                        _inProgressReservation.ProvidedService.PunctureRepair = true;
                        break;
                    case ServiceTypes.SuspensionAdjustment:
                        _inProgressReservation.ProvidedService.SuspensionAdjustment = true;
                        break;
                    default:
                        break;
                }

                ViewBag.ChosenShop = _inProgressReservation.Workshop.Name;
                ViewBag.ServiceType = serviceType;
                ViewBag.ChosenDate = _inProgressReservation.ReservationTime;

                HttpContext.Session.SetString(_service.SShopID, ID.ToString());
                HttpContext.Session.SetString(_service.SServiceType, serviceType.ToString());
                HttpContext.Session.SetString(_service.STime, chosenDate.ToString("yyyMMddHHmmss"));

                return View(_inProgressReservation);
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create()
        {
            CultureInfo provider = CultureInfo.InvariantCulture;
            var shopID = HttpContext.Session.GetString(_service.SShopID);
            
            if (shopID == null)
            {
                return NotFound();
            }

            var serviceType = (ServiceTypes)Enum.Parse(typeof(ServiceTypes), HttpContext.Session.GetString(_service.SServiceType));
            var time = DateTime.ParseExact(HttpContext.Session.GetString(_service.STime), "yyyyMMddHHmmss", provider);

            CarServices st = new CarServices();

            switch (serviceType)
            {
                case ServiceTypes.TireReplacement:
                    st.TireReplacement = true;
                    break;
                case ServiceTypes.AirConCharging:
                    st.AirConCharging = true;
                    break;
                case ServiceTypes.PunctureRepair:
                    st.PunctureRepair = true;
                    break;
                case ServiceTypes.SuspensionAdjustment:
                    st.SuspensionAdjustment = true;
                    break;
                default:
                    break;
            }

            var shop = _service.GetWorkShopByID(Int32.Parse(shopID));

            if (shop == null)
            {
                return NotFound();
            }

            Reservation reservation = new Reservation();
            reservation.ReservationTime = time;
            reservation.UserID = Int32.Parse(_userManager.GetUserId(User));
            reservation.ProvidedService = st;

            foreach (var res in shop.Reservations)
            {
                if (res.ReservationTime == reservation.ReservationTime &&
                    res.Workshop.ID == reservation.Workshop.ID &&
                    res.ProvidedService == reservation.ProvidedService)
                {
                    return RedirectToAction("index", "home");
                }
            }

            shop.Reservations.Add(reservation);

            if (_service.UpdateWorkshop(shop))
            {
                return RedirectToAction("index", "home");
            }

            return View();
        }
    }
}

CarTireRepairService/Controllers/WorkshopsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System;
using Persistence.Services;

namespace CarTireRepairService.Controllers
{
    [Authorize]
    public class WorkshopsController : Controller
    {
        private readonly CTRService _service;

        public WorkshopsController(CTRService service)
        {
            _service = service;
        }

        // GET: Workshops
        [AllowAnonymous]
        public IActionResult Index(string searchString = null)
        {
            ViewData["CurrentFilter"] = searchString;
            return View(_service.GetWorkshops(searchString));
        }

        public IActionResult Details(Int32 ID)
        {
            try
            {
                var workshop = _service.GetWorkShopByID(ID);
                return View(workshop);
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
        }
    }
}

CarTireRepairService/Views/Reservations/Create.cshtml
@model Persistence.Models.Reservation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Confirm Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <div class="form-group">
                    <label class="control-label">Car repair shop name:</label>
                    <p class="font-weight-bold">@ViewBag.ChosenShop</p>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Ordered service:</label>
                <p class="font-weight-bold">
                    @if (Model.ProvidedService.TireReplacement)
                    {
                        @Html.DisplayNameFor(model => model.ProvidedService.TireReplacement)
                    }
                    else if (Model.ProvidedService.AirConCharging)
                    {
                        @Html.DisplayNameFor(model => model.ProvidedService.AirConCharging)
                    }
                    else if (Model.ProvidedService.PunctureRepair)
                    {
                        @Html.DisplayNameFor(model => model.ProvidedService.PunctureRepair)
                    }
                    else if (Model.ProvidedService.SuspensionAdjustment)
                    {
                        @Html.DisplayNameFor(model => model.ProvidedService.SuspensionAdjustment)
                    }
                </p>

            </div>
            <div class="form-group">
                <label class="control-label">Repair time and date:</label>
                <p class="font-weight-bold">@ViewBag.ChosenDate</p>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Workshops" asp-action="Index">Nvm.. Back to the workshops</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarTireRepairService/Views/Reservations/Delete.cshtml
@model Persistence.Models.Reservation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarTireRepairService/Views/Reservations/Details.cshtml
@model Persistence.Models.Reservation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarTireRepairService/Views/Reservations/Edit.cshtml
@model Persistence.Models.Reservation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ReservationTime" class="control-label"></label>
                <input asp-for="ReservationTime" class="form-control" />
                <span asp-validation-for="ReservationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarTireRepairService/Views/Reservations/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList;
@model IPagedList<DateTime>

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Available Reservations";
}

<h1>Available Reservations</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(modelItem => DateTime.Now.Year)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item
                </td>
                <td>
                    |
                </td>
                <td>
                    <a asp-controller="Reservations" asp-action="Create"
                       asp-route-chosenDateTime="@item.ToString("yyyMMddHHmmss")"
                       asp-route-id="@ViewBag.ID"
                       asp-route-serviceType="@ViewBag.ServiceType"
                       >Reserv it for me</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))